version: '3'
services:
  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - "/home/open/mymongo:/data/db"
    networks:
      credtodos-network:
        ipv4_address: 192.168.0.10

networks:
  credtodos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24